[theme]
primaryColor="#3A6EA5"
backgroundColor="#F4F6FB"
secondaryBackgroundColor="#DCE6F2"
textColor="#222831"
font = "Verdana"
codeFont = "JetBrains Mono:https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap"
